X=MsgBox("time to get my revenge >:), caillou!",1+16,"user")
X=MsgBox("you dumb *ss, nou!",1+16,"kaylou")
X=MsgBox("you dumb *ss, nou!",1+16,"kaylou")
X=MsgBox("you dumb *ss, nou!",1+16,"kaylou")
X=MsgBox("you dumb *ss, nou!",1+16,"kaylou")
